"use client";

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import type { ProviderAnalysisResult } from "@/app/api/ai/provider-analyzer/route";

const DEMAND_CONFIG = {
  very_high: { label: "Very High", color: "#dc2626", bg: "#fef2f2", width: "100%" },
  high:      { label: "High",      color: "#d97706", bg: "#fff7ed", width: "75%"  },
  medium:    { label: "Medium",    color: "#1a56a0", bg: "#eff6ff", width: "50%"  },
  low:       { label: "Low",       color: "#64748b", bg: "#f8fafc", width: "25%"  },
};

function DemandGauge({ score }: { score: number }) {
  const color = score >= 70 ? "#16a34a" : score >= 40 ? "#d97706" : "#64748b";
  const label = score >= 70 ? "Strong Opportunity" : score >= 40 ? "Moderate Opportunity" : "Emerging Market";

  return (
    <div className="flex flex-col items-center">
      <div className="relative w-28 h-28">
        <svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
          <circle cx="50" cy="50" r="40" fill="none" stroke="#e2e8f0" strokeWidth="10" />
          <motion.circle
            cx="50" cy="50" r="40"
            fill="none"
            stroke={color}
            strokeWidth="10"
            strokeLinecap="round"
            strokeDasharray={`${(score / 100) * 251} 251`}
            initial={{ strokeDasharray: "0 251" }}
            animate={{ strokeDasharray: `${(score / 100) * 251} 251` }}
            transition={{ duration: 1.2, ease: "easeOut" }}
          />
        </svg>
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span className="text-2xl font-bold" style={{ color }}>{score}</span>
          <span className="text-[9px] text-[#64748b] font-medium">/ 100</span>
        </div>
      </div>
      <span className="text-xs font-semibold mt-2" style={{ color }}>{label}</span>
    </div>
  );
}

function downloadReport(result: ProviderAnalysisResult, orgName: string) {
  const content = `HAYYA MED PRO — TRAINING PROVIDER AI INTELLIGENCE REPORT
Organization: ${orgName}
Generated: ${new Date().toLocaleString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

MARKET OPPORTUNITY SCORE: ${result.demandScore}/100

EXECUTIVE SUMMARY
${result.summary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TOP DEMANDED SPECIALTIES
${result.topDemandedSpecialties.map((s, i) => `${i + 1}. ${s}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GAP OPPORTUNITIES
${result.gapOpportunities.map((g) => `[${g.demandLevel.toUpperCase()}] ${g.area}
  Est. monthly learners: ${g.estimatedMonthlyLearners}
  Action: ${g.recommendedAction}`).join("\n\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REVENUE INSIGHTS
High-value categories: ${result.revenueInsights.highValueCategories.join(", ")}
Suggested pricing: ${result.revenueInsights.suggestedPricingTier}
Monthly revenue potential: ${result.revenueInsights.estimatedMonthlyRevenuePotential}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STRATEGIC RECOMMENDATIONS
${result.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report is generated by Hayya Med AI based on anonymized, aggregated platform data.
Verify all market estimates independently before making business decisions.
`;
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `hayya-provider-intelligence-${new Date().toISOString().slice(0, 10)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ProviderAIAnalyzerPage() {
  const [orgId, setOrgId] = useState<string | null>(null);
  const [orgName, setOrgName] = useState("Your Organization");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ProviderAnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [analysisType, setAnalysisType] = useState<"full_report" | "demand_prediction" | "gap_analysis" | "revenue_report">("full_report");

  useEffect(() => {
    fetch("/api/provider/org-id")
      .then((r) => r.json())
      .then((d) => {
        if (d.organizationId) { setOrgId(d.organizationId); setOrgName(d.name ?? "Your Organization"); }
      })
      .catch(() => {});
  }, []);

  const runAnalysis = useCallback(async () => {
    if (!orgId) { setError("Organization not found."); return; }
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch("/api/ai/provider-analyzer", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ organizationId: orgId, analysisType }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error ?? "Analysis failed."); return; }
      setResult(data);
    } catch {
      setError("Connection error. Please try again.");
    } finally {
      setLoading(false);
    }
  }, [orgId, analysisType]);

  const analysisOptions = [
    { value: "full_report", label: "Full Intelligence Report" },
    { value: "demand_prediction", label: "Demand Prediction" },
    { value: "gap_analysis", label: "Gap Analysis" },
    { value: "revenue_report", label: "Revenue Insights" },
  ] as const;

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-xs font-semibold text-[#1a56a0] uppercase tracking-wide">Hayya Med AI</span>
          <span className="text-[#e2e8f0]">·</span>
          <span className="text-xs text-[#64748b]">Provider Intelligence</span>
        </div>
        <h1 className="text-2xl font-bold text-[#0f1f3d]">Training Provider AI Analyzer</h1>
        <p className="text-sm text-[#64748b] mt-1">
          Market demand prediction, curriculum gap analysis, and revenue optimization — powered by Hayya Med AI.
        </p>
      </div>

      {/* Controls */}
      <div className="bg-white border border-[#e2e8f0] rounded-2xl p-6 mb-6 shadow-sm">
        <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-end">
          <div className="flex-1">
            <label className="text-xs font-semibold text-[#374151] mb-2 block">Analysis Mode</label>
            <div className="flex flex-wrap gap-2">
              {analysisOptions.map((opt) => (
                <button
                  key={opt.value}
                  type="button"
                  onClick={() => setAnalysisType(opt.value)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all ${
                    analysisType === opt.value
                      ? "bg-[#1a56a0] text-white border-[#1a56a0]"
                      : "bg-white text-[#374151] border-[#e2e8f0] hover:border-[#1a56a0]"
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>
          <button
            type="button"
            onClick={runAnalysis}
            disabled={loading || !orgId}
            className="flex items-center gap-2 px-5 py-2.5 bg-[#1a56a0] text-white text-sm font-semibold rounded-xl hover:bg-[#1e3a6e] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                Analyzing…
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3v11.25A2.25 2.25 0 0 0 6 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0 1 18 16.5h-2.25m-7.5 0h7.5m-7.5 0-1 3m8.5-3 1 3m0 0 .5 1.5m-.5-1.5h-9.5m0 0-.5 1.5m.75-9 3-3 2.148 2.148A12.061 12.061 0 0 1 16.5 7.605" />
                </svg>
                Run AI Analysis
              </>
            )}
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-[#fef2f2] border border-[#fca5a5] rounded-xl p-4 mb-6 text-sm text-[#dc2626]">
          {error}
        </div>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center py-16 gap-4">
          <div className="relative w-16 h-16">
            <div className="absolute inset-0 rounded-full border-4 border-[#e2e8f0]" />
            <div className="absolute inset-0 rounded-full border-4 border-t-[#1a56a0] animate-spin" />
          </div>
          <p className="text-sm text-[#64748b] font-medium">Analyzing market signals with Hayya Med AI…</p>
        </div>
      )}

      <AnimatePresence>
        {result && !loading && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="space-y-5"
          >
            {/* Summary + demand gauge */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              <div className="md:col-span-2 bg-white border border-[#e2e8f0] rounded-2xl p-6 shadow-sm">
                <h2 className="text-xs font-semibold text-[#64748b] uppercase tracking-wide mb-3">Market Intelligence Summary</h2>
                <p className="text-sm text-[#374151] leading-relaxed">{result.summary}</p>
                <div className="mt-4">
                  <h3 className="text-xs font-semibold text-[#374151] mb-2">Top Demanded Specialties</h3>
                  <div className="flex flex-wrap gap-2">
                    {result.topDemandedSpecialties.map((s, i) => (
                      <span key={i} className="text-xs bg-[#eff6ff] text-[#1a56a0] border border-[#bfdbfe] px-2.5 py-1 rounded-full font-medium">
                        {s}
                      </span>
                    ))}
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => downloadReport(result, orgName)}
                  className="flex items-center gap-1.5 text-xs font-semibold text-[#1a56a0] hover:text-[#1e3a6e] mt-4 transition-colors"
                >
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                  </svg>
                  Download Intelligence Report
                </button>
              </div>

              <div className="bg-white border border-[#e2e8f0] rounded-2xl p-6 shadow-sm flex flex-col items-center justify-center">
                <h2 className="text-xs font-semibold text-[#64748b] uppercase tracking-wide mb-4">Market Demand Score</h2>
                <DemandGauge score={result.demandScore} />
              </div>
            </div>

            {/* Gap Opportunities */}
            <div className="bg-white border border-[#e2e8f0] rounded-2xl p-6 shadow-sm">
              <h2 className="text-xs font-semibold text-[#64748b] uppercase tracking-wide mb-4">
                Curriculum Gap Opportunities
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {result.gapOpportunities.map((gap, i) => {
                  const d = DEMAND_CONFIG[gap.demandLevel];
                  return (
                    <motion.div
                      key={i}
                      initial={{ opacity: 0, y: 12 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: i * 0.08 }}
                      className="border border-[#e2e8f0] rounded-xl p-4"
                      style={{ background: d.bg }}
                    >
                      <div className="flex items-start justify-between mb-2">
                        <h3 className="text-sm font-semibold text-[#0f1f3d]">{gap.area}</h3>
                        <span
                          className="text-[10px] font-bold px-2 py-0.5 rounded-full flex-shrink-0 ml-2"
                          style={{ background: d.color + "20", color: d.color }}
                        >
                          {d.label}
                        </span>
                      </div>
                      <div className="mb-2">
                        <div className="flex items-center justify-between text-[10px] text-[#64748b] mb-1">
                          <span>Market demand</span>
                          <span>{gap.estimatedMonthlyLearners} learners/mo</span>
                        </div>
                        <div className="h-1.5 rounded-full bg-white/60">
                          <motion.div
                            className="h-full rounded-full"
                            style={{ background: d.color }}
                            initial={{ width: 0 }}
                            animate={{ width: d.width }}
                            transition={{ delay: i * 0.08 + 0.3, duration: 0.5 }}
                          />
                        </div>
                      </div>
                      <p className="text-xs text-[#374151]">{gap.recommendedAction}</p>
                    </motion.div>
                  );
                })}
              </div>
            </div>

            {/* Revenue insights */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              <div className="md:col-span-2 bg-white border border-[#e2e8f0] rounded-2xl p-6 shadow-sm">
                <h2 className="text-xs font-semibold text-[#64748b] uppercase tracking-wide mb-4">Revenue Insights</h2>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
                  <div className="bg-[#f8fafc] rounded-xl p-3">
                    <p className="text-[10px] text-[#64748b] font-medium mb-1">Suggested Pricing</p>
                    <p className="text-sm font-bold text-[#1a56a0]">{result.revenueInsights.suggestedPricingTier}</p>
                  </div>
                  <div className="bg-[#f0fdf4] rounded-xl p-3 sm:col-span-2">
                    <p className="text-[10px] text-[#64748b] font-medium mb-1">Monthly Revenue Potential</p>
                    <p className="text-sm font-bold text-[#16a34a]">{result.revenueInsights.estimatedMonthlyRevenuePotential}</p>
                  </div>
                </div>
                <div>
                  <p className="text-xs font-semibold text-[#374151] mb-2">High-Value Course Categories</p>
                  <div className="flex flex-wrap gap-2">
                    {result.revenueInsights.highValueCategories.map((c, i) => (
                      <span key={i} className="text-xs bg-[#f0fdf4] text-[#16a34a] border border-[#bbf7d0] px-2.5 py-1 rounded-full font-medium">
                        {c}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <div className="bg-white border border-[#e2e8f0] rounded-2xl p-6 shadow-sm">
                <h2 className="text-xs font-semibold text-[#64748b] uppercase tracking-wide mb-4">Strategic Actions</h2>
                <ol className="space-y-3">
                  {result.recommendations.map((rec, i) => (
                    <motion.li
                      key={i}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: i * 0.1 }}
                      className="flex items-start gap-2.5"
                    >
                      <span className="w-5 h-5 rounded-full bg-[#1a56a0]/10 text-[#1a56a0] text-[10px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                        {i + 1}
                      </span>
                      <span className="text-xs text-[#374151] leading-relaxed">{rec}</span>
                    </motion.li>
                  ))}
                </ol>
              </div>
            </div>

            <p className="text-[10px] text-[#94a3b8] text-center leading-relaxed">
              Market estimates are based on anonymized, aggregated platform data and GCC healthcare compliance patterns.
              Verify all projections independently before making business decisions.
            </p>
          </motion.div>
        )}
      </AnimatePresence>

      {!result && !loading && !error && (
        <div className="text-center py-16 text-[#94a3b8]">
          <svg className="w-12 h-12 mx-auto mb-4 text-[#e2e8f0]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3v11.25A2.25 2.25 0 0 0 6 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0 1 18 16.5h-2.25m-7.5 0h7.5m-7.5 0-1 3m8.5-3 1 3m0 0 .5 1.5m-.5-1.5h-9.5m0 0-.5 1.5m.75-9 3-3 2.148 2.148A12.061 12.061 0 0 1 16.5 7.605" />
          </svg>
          <p className="text-sm font-medium">Select an analysis mode and run AI Analysis</p>
          <p className="text-xs mt-1">Market demand signals, curriculum gaps, and revenue insights will appear here</p>
        </div>
      )}
    </div>
  );
}
