import { MetadataRoute } from "next";

const BASE = "https://hayyamed.pro";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: BASE,                      lastModified: new Date(), changeFrequency: "weekly",  priority: 1.0 },
    { url: `${BASE}/pricing`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/register`,        lastModified: new Date(), changeFrequency: "yearly",  priority: 0.8 },
    { url: `${BASE}/login`,           lastModified: new Date(), changeFrequency: "yearly",  priority: 0.5 },
    { url: `${BASE}/forgot-password`, lastModified: new Date(), changeFrequency: "yearly",  priority: 0.3 },
    { url: `${BASE}/about`,           lastModified: new Date(), changeFrequency: "yearly",  priority: 0.7 },
    { url: `${BASE}/help`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE}/changelog`,       lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE}/contact`,         lastModified: new Date(), changeFrequency: "yearly",  priority: 0.5 },
    { url: `${BASE}/terms`,           lastModified: new Date(), changeFrequency: "yearly",  priority: 0.3 },
    { url: `${BASE}/privacy`,         lastModified: new Date(), changeFrequency: "yearly",  priority: 0.3 },
    { url: `${BASE}/legal/dpa`,       lastModified: new Date(), changeFrequency: "yearly",  priority: 0.2 },
    { url: `${BASE}/qchp`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/scfhs`,           lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/dha`,             lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/doh`,              lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/moh-kuwait`,       lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/nhra`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/omsb`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/employers`,        lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/countries`,        lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/physician-cme`,    lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/nurse-cpd`,        lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/pharmacist-cme`,   lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/cme-vs-cpd`,       lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/dentist-cme`,       lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/allied-health-cpd`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/cme-tracker`,       lastModified: new Date(), changeFrequency: "monthly", priority: 0.95 },
    { url: `${BASE}/cpd-tracker`,       lastModified: new Date(), changeFrequency: "monthly", priority: 0.95 },
    { url: `${BASE}/request-demo`,      lastModified: new Date(), changeFrequency: "yearly",  priority: 0.7 },
    { url: `${BASE}/qchp-renewal`,      lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/scfhs-renewal`,                lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/dha-renewal`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/doh-renewal`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/nhra-renewal`,                   lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/omsb-renewal`,                   lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/moh-kuwait-renewal`,             lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/gcc-medical-license-renewal`,    lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/healthcare-compliance-software`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/cme-compliance-report`,          lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/for-providers`,                  lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/for-universities`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/cardiology-cme`,                 lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/internal-medicine-cme`,          lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/emergency-medicine-cme`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/surgery-cme`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/pediatrics-cme`,                 lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/radiology-cme`,                  lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/psychiatry-cme`,                 lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/obstetrics-gynecology-cme`,      lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/anesthesia-cme`,                 lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/orthopedics-cme`,                lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/family-medicine-cme`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/gcc-cme-requirements`,           lastModified: new Date(), changeFrequency: "monthly", priority: 0.95 },
    { url: `${BASE}/gmc-cpd`,                        lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/ahpra-cpd`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/nmc-india-cme`,                  lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/dermatology-cme`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/neurology-cme`,                 lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/nephrology-cme`,                lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/ophthalmology-cme`,             lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/egypt-cme`,                     lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/jordan-cme`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/global-cme-requirements`,       lastModified: new Date(), changeFrequency: "monthly", priority: 0.95 },
  ];
}
