import { createClient, createAdminClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { getUserPlan, isPro } from "@/lib/subscription";
import PathwayClient from "@/components/dashboard/PathwayClient";
import Link from "next/link";

export const metadata = {
  title: "AI Learning Pathway — Hayya Med Pro",
  description: "AI-generated 12-month CME learning plan personalised to your compliance gap and specialty.",
};

export default async function LearningPathwayPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const [plan, profileRes] = await Promise.all([
    getUserPlan(user.id),
    createAdminClient()
      .from("professional_profiles")
      .select("profession, specialty, country_of_residence")
      .eq("auth_id", user.id)
      .maybeSingle(),
  ]);

  if (!isPro(plan)) {
    return (
      <div className="max-w-xl mx-auto mt-16 text-center px-4">
        <div className="text-5xl mb-4">🗺️</div>
        <h1 className="text-xl font-bold text-[#111] mb-2">AI Learning Pathway</h1>
        <p className="text-sm text-[#64748b] mb-2">
          Get a personalised 12-month CPD/CME plan generated by AI — month-by-month targets,
          activity recommendations, and conference tips tailored to your specialty and country.
        </p>
        <p className="text-xs text-[#94a3b8] mb-6">Available on the Pro plan.</p>
        <a
          href="/pricing?source=learning_pathway"
          className="inline-block bg-[#1a56a0] text-white text-sm font-semibold px-6 py-3 rounded-xl hover:bg-[#1547a0] transition-colors"
        >
          Upgrade to Pro →
        </a>
        <p className="text-xs text-[#94a3b8] mt-4">
          <Link href="/dashboard/cme" className="hover:underline">← Back to CME Dashboard</Link>
        </p>
      </div>
    );
  }

  const admin = createAdminClient();
  const [walletsRes] = await Promise.all([
    admin.from("cme_wallets").select("*").eq("professional_id", user.id).order("created_at", { ascending: true }),
  ]);

  const wallets = walletsRes.data ?? [];
  const wallet = wallets[0] ?? null;

  // Fetch category breakdown for the primary wallet
  let gaps: { category: string; earned: number; needed: number }[] = [];

  if (wallet) {
    const countryCode = wallet.country === "Qatar" ? "QA"
      : wallet.country === "Saudi Arabia" ? "SA"
      : wallet.country === "UAE" ? "AE-DU"
      : wallet.country === "Kuwait" ? "KW"
      : wallet.country === "Bahrain" ? "BH"
      : wallet.country === "Oman" ? "OM"
      : "QA";

    const [activitiesRes, catRulesRes] = await Promise.all([
      admin
        .from("cme_activities")
        .select("credits, category, verification_status")
        .eq("professional_id", user.id)
        .eq("wallet_id", wallet.id),
      admin
        .from("compliance_activity_categories")
        .select("category_name, min_credits_per_cycle")
        .eq("country_code", countryCode)
        .gt("min_credits_per_cycle", 0),
    ]);

    const activities = activitiesRes.data ?? [];
    const creditsByCategory: Record<string, number> = {};
    for (const a of activities.filter((x) => x.verification_status !== "rejected")) {
      if (a.category) creditsByCategory[a.category] = (creditsByCategory[a.category] ?? 0) + Number(a.credits);
    }

    gaps = (catRulesRes.data ?? []).map((r) => ({
      category: r.category_name,
      earned: creditsByCategory[r.category_name] ?? 0,
      needed: Math.max(0, r.min_credits_per_cycle - (creditsByCategory[r.category_name] ?? 0)),
    })).filter((g) => g.needed > 0);
  }

  const initialData = wallet
    ? {
        profession:        profileRes.data?.profession ?? "Healthcare Professional",
        specialty:         profileRes.data?.specialty ?? null,
        country:           wallet.country ?? profileRes.data?.country_of_residence ?? "Qatar",
        requiredCredits:   wallet.required_credits ?? 80,
        completedCredits:  wallet.completed_credits ?? 0,
        cycleEndDate:      wallet.cycle_end_date ?? null,
        gaps,
      }
    : null;

  return (
    <div>
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-1">
          <Link href="/dashboard/cme" className="text-xs text-[#64748b] hover:text-[#374151]">
            ← CME Dashboard
          </Link>
        </div>
        <h1 className="text-2xl font-bold text-[#111] mb-1">AI Learning Pathway</h1>
        <p className="text-sm text-[#64748b]">
          Personalised 12-month CPD/CME plan generated by AI — with monthly targets, activity types,
          and conference tips tailored to your specialty and country.
        </p>
      </div>

      <PathwayClient initialData={initialData} />
    </div>
  );
}
